language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"

jobs:
  include:
    - name: "Lint"
      python: "2.7"
      script: ./lint.sh all

before_install:
  - which awk
  - curl -sL https://firebase.tools | flags="install-binary-release" bash -x
script:
  - pytest
  - firebase emulators:exec --only database --project fake-project-id 'pytest integration/test_db.py'
cache:
  pip: true
  npm: true
  directories:
  - $HOME/.cache/firebase/emulators
