language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"

jobs:
  include:
    - name: "Lint"
      python: "2.7"
      script: ./lint.sh all

before_install:
  - nvm install 8 && npm install -g firebase-tools
script:
  - pytest
  - firebase emulators:exec --only database --project fake-project-id 'pytest integration/test_db.py'
cache:
  pip: true
  npm: true
  directories:
  - $HOME/.cache/firebase/emulators
